### ISSUE TITLE
Ctrl-t transpose is buggy

### ISSUE THREAD

**Issue by rhubarbdog** [ntoll/microrepl#25]
i miss typed a statement, i cursored back to the error press Ctrl-t to tanspose characters as in bash and emacs.
i press enter it states
```
dispa--- unknown menu character Ctrl+J --
```

the characters did switch on the screen

**Comment by ntoll** [comment]
Put simply, MicroPython (which is the thing that traps such characters, microrepl is just a dumb terminal) probably doesn't support `Ctrl-t`. Please remember that MicroPython runs in a very limited context and so may not support everything you're used to having in bash or emacs.

Thanks for reporting this. Again, it's useful if others encounter this problem... they'll find this response. Closing this since it's a MicroPython related thing rather than anything to do with microrepl. Season's greetings (again, again, again). :gift:
