### ISSUE TITLE
On Mac OS X ctrl+] doesn't work

### ISSUE THREAD

**Issue by jneves** [ntoll/microrepl#4]
On Max OS X ctrl+] doesn't work to exit microrepl. Maybe ctrl+d to close it?

**Comment by ncoghlan** [comment]
Ctrl+d issued a soft-reboot for me on Linux - the only way I found to exit was disconnecting the micro:bit

**Comment by ncoghlan** [comment]
Err, nevermind - this time I actually read the REPL banner, and Ctrl+] works fine in an Ubuntu Docker container. Sorry for the noise.

**Comment by ntoll** [comment]
@jneves did you try cmd+] ..? I'll dig out a Mac and try it for myself.

**Comment by jneves** [comment]
Yes, didn't work. 

On 17 January 2016 16:18:57 GMT+00:00, Nicholas Tollervey notifications@github.com wrote:

> @jneves did you try cmd+] ..? I'll dig out a Mac and try it for myself.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ntoll/microrepl/issues/4#issuecomment-172346324

## 

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by ntoll** [comment]
OK... I'll find some time this week to investigate and (hopefully) fix.

**Comment by carlosperate** [comment]
Having the same problem on macOS, looks like `Ctrl+]` sends the ASCII Group Separator control chracter (http://www.theasciicode.com.ar/ascii-control-characters/group-separator-ascii-code-29.html).

That's what miniterm should intercepts before sending to the serial ([serial/tools/miniterm.py#L350](https://github.com/pyserial/pyserial/blob/92d101613be41ecb2f2054c3f43a006fbe6f9966/serial/tools/miniterm.py#L350) and [serial/tools/miniterm.py#L467-L480](https://github.com/pyserial/pyserial/blob/92d101613be41ecb2f2054c3f43a006fbe6f9966/serial/tools/miniterm.py#L467-L480)), and using miniterm on it's own works with fine. So with the following command miniterm exists succesfully when `Ctrl+]` is entered:

```
python3 serial/tools/miniterm.py <microbit_port> 115200
```

**Comment by carlosperate** [comment]
Turns out this is partially because PySerial v3 has changed miniterm affecting the way we configure it (https://github.com/pyserial/pyserial/commit/442bf51bf9fa906b4600d2e99a4b83b8ed26c98e), and because the miniterm constructor has a bug: https://github.com/pyserial/pyserial/pull/324

I'm surprised this worked in Windows or Linux, as this shoudn't be a platform specific issue. Maybe we haven't tested it on the other playforms with PySerial v3?

We still need to update microrepl to set it's own exit character as it does for PySerial v2. I'll submit a PR here a bit later today once I have a chance to test it in more environments.

**Comment by carlosperate** [comment]
Created PR #15 to fix this issue.

I've tested microrepl on Windows, and ctrl+] is not working there either, so this is not a macOS only issue. There a separate issue on Windows that I had to fix first, so I've also created #17 to do that.

**Comment by ntoll** [comment]
Solution merged.
